  name: hello_world.yml
  on:
    push:
      branches: [ main ]
    pull_request:
      branches: [ main ]
  
  permissions: {}
  
  jobs:
    hello-world-job:
      if: ${{ needs.check-paths.outputs.run-job == 'true' }}
      runs-on: ubuntu-latest
      name: A job to say hello
      steps:
        - name: Say hello
          run: echo Hello world!

    example-summary:
      runs-on: ubuntu-latest
      steps:
        - name: Output Some Markdown Code in Summary 👀
          run: |
            {
              echo '# Yay, you ran this workflow! 🎉'
              echo ''
              echo '## Workflow Details'
              echo '- Branch: ${{ github.ref }}'
              echo '- Commit: ${{ github.sha }}'
              echo '- Actor: ${{ github.actor }}'
              echo ''
              echo '```'
            } >> $GITHUB_STEP_SUMMARY
