  name: hello_world.yml
  on:
    push:
      branches: [ main ]
    pull_request:
      branches: [ main ]
  
  permissions: {}
  
  jobs:
    hello-world-job:
      runs-on: ubuntu-latest
      name: A job to say hello
      steps:
        - name: Say hello
          run: echo Hello world!

    first-summary:
      runs-on: ubuntu-latest
      steps:
        - name: Output Some Markdown Code in Summary 👀
          run: |
            {
              echo '# This is the first step summary! 🎉'
              echo ''
              echo '## Workflow Details'
              echo '- Branch: ${{ github.ref }}'
              echo '- Commit: ${{ github.sha }}'
              echo '- Actor: ${{ github.actor }}'
              echo ''
              echo '```'
            } >> $GITHUB_STEP_SUMMARY

    second-summary:
        runs-on: ubuntu-latest
        steps:
          - name: Output Some Markdown Code in Summary 👀
            run: |
              {
                echo '# This is the second step summary! 🎉'
                echo ''
                echo '```'
              } >> $GITHUB_STEP_SUMMARY
